### ISSUE TITLE
compiling so3

### ISSUE THREAD

**Issue by pwschuck** [astro-informatics/so3-archive#1] opened 2015-11-13 13:36 UTC
Hi, 

I'm trying to compile so3 and I  get the following errors on 'make all' (seems like I'm missing an include file?). Any help would be greatly appreciated.

Thanks,

-- Pete

 make all
icc -Wall  -O3 -fopenmp -DSO3_VERSION=\"0.1\" -DSO3_BUILD=\"`svnversion -n .`\" -I/data/software/sphwvlts//../fftw/fftw-3.3.4//include -I/data/software/sphwvlts//ssht/include/c -I/data/software/sphwvlts//so3/include/c -fPIC -c /data/software/sphwvlts//so3/src/c/so3_core.c -o /data/software/sphwvlts//so3/src/c/so3_core.o
/data/software/sphwvlts//so3/src/c/so3_core.c(100): error: identifier "ssht_core_mw_lb_inverse_sov_sym" is undefined
          ssht = ssht_core_mw_lb_inverse_sov_sym;
                 ^

/data/software/sphwvlts//so3/src/c/so3_core.c(104): error: identifier "ssht_core_mw_lb_inverse_sov_sym_ss" is undefined
          ssht = ssht_core_mw_lb_inverse_sov_sym_ss;
                 ^

/data/software/sphwvlts//so3/src/c/so3_core.c(305): error: identifier "ssht_core_mw_lb_forward_sov_conv_sym" is undefined
          ssht = ssht_core_mw_lb_forward_sov_conv_sym;
                 ^

/data/software/sphwvlts//so3/src/c/so3_core.c(309): error: identifier "ssht_core_mw_lb_forward_sov_conv_sym_ss" is undefined
          ssht = ssht_core_mw_lb_forward_sov_conv_sym_ss;
                 ^

/data/software/sphwvlts//so3/src/c/so3_core.c(526): error: identifier "ssht_core_mw_lb_inverse_sov_sym" is undefined
          complex_ssht = ssht_core_mw_lb_inverse_sov_sym;
                         ^

/data/software/sphwvlts//so3/src/c/so3_core.c(527): error: identifier "ssht_core_mw_lb_inverse_sov_sym_real" is undefined
          real_ssht = ssht_core_mw_lb_inverse_sov_sym_real;
                      ^

/data/software/sphwvlts//so3/src/c/so3_core.c(531): error: identifier "ssht_core_mw_lb_inverse_sov_sym_ss" is undefined
          complex_ssht = ssht_core_mw_lb_inverse_sov_sym_ss;
                         ^

/data/software/sphwvlts//so3/src/c/so3_core.c(532): error: identifier "ssht_core_mw_lb_inverse_sov_sym_ss_real" is undefined
          real_ssht = ssht_core_mw_lb_inverse_sov_sym_ss_real;
                      ^

/data/software/sphwvlts//so3/src/c/so3_core.c(752): error: identifier "ssht_core_mw_lb_forward_sov_conv_sym" is undefined
          complex_ssht = ssht_core_mw_lb_forward_sov_conv_sym;
                         ^

/data/software/sphwvlts//so3/src/c/so3_core.c(753): error: identifier "ssht_core_mw_lb_forward_sov_conv_sym_real" is undefined
          real_ssht = ssht_core_mw_lb_forward_sov_conv_sym_real;
                      ^

/data/software/sphwvlts//so3/src/c/so3_core.c(757): error: identifier "ssht_core_mw_lb_forward_sov_conv_sym_ss" is undefined
          complex_ssht = ssht_core_mw_lb_forward_sov_conv_sym_ss;
                         ^

/data/software/sphwvlts//so3/src/c/so3_core.c(758): error: identifier "ssht_core_mw_lb_forward_sov_conv_sym_ss_real" is undefined
          real_ssht = ssht_core_mw_lb_forward_sov_conv_sym_ss_real;
                      ^

compilation aborted for /data/software/sphwvlts//so3/src/c/so3_core.c (code 2)
make: **\* [/data/software/sphwvlts//so3/src/c/so3_core.o] Error 2

**Comment by ixkael** [comment] 2015-11-13 13:38
Hi,
I've never seem these errors before but I have never compile these codes with icc, which might have a different convention for function pointers. Would you mind trying to compile with gcc?

**Comment by pwschuck** [comment] 2015-11-13 13:42
Hi Boris,

thanks for your quick reply

I rebuild ssht with gcc and no problem (same with icc)

after that build here is the output for so3

thanks,

-- Pete

make
gcc -Wall  -O3 -fopenmp -DSO3_VERSION=\"0.1\" -DSO3_BUILD=\"`svnversion
-n .`\" -I/data/software/sphwvlts//../fftw/fftw-3.3.4//include
-I/data/software/sphwvlts//ssht/include/c
-I/data/software/sphwvlts//so3/include/c -fPIC -c
/data/software/sphwvlts//so3/src/c/so3_core.c -o
/data/software/sphwvlts//so3/src/c/so3_core.o
/data/software/sphwvlts//so3/src/c/so3_core.c: In function
‘so3_core_inverse_via_ssht’:
/data/software/sphwvlts//so3/src/c/so3_core.c:100:16: error:
‘ssht_core_mw_lb_inverse_sov_sym’ undeclared (first use in this function)
         ssht = ssht_core_mw_lb_inverse_sov_sym;
                ^
/data/software/sphwvlts//so3/src/c/so3_core.c:100:16: note: each
undeclared identifier is reported only once for each function it appears in
/data/software/sphwvlts//so3/src/c/so3_core.c:104:16: error:
‘ssht_core_mw_lb_inverse_sov_sym_ss’ undeclared (first use in this function)
         ssht = ssht_core_mw_lb_inverse_sov_sym_ss;
                ^
/data/software/sphwvlts//so3/src/c/so3_core.c: In function
‘so3_core_forward_via_ssht’:
/data/software/sphwvlts//so3/src/c/so3_core.c:305:16: error:
‘ssht_core_mw_lb_forward_sov_conv_sym’ undeclared (first use in this
function)
         ssht = ssht_core_mw_lb_forward_sov_conv_sym;
                ^
/data/software/sphwvlts//so3/src/c/so3_core.c:309:16: error:
‘ssht_core_mw_lb_forward_sov_conv_sym_ss’ undeclared (first use in this
function)
         ssht = ssht_core_mw_lb_forward_sov_conv_sym_ss;
                ^
/data/software/sphwvlts//so3/src/c/so3_core.c: In function
‘so3_core_inverse_via_ssht_real’:
/data/software/sphwvlts//so3/src/c/so3_core.c:526:24: error:
‘ssht_core_mw_lb_inverse_sov_sym’ undeclared (first use in this function)
         complex_ssht = ssht_core_mw_lb_inverse_sov_sym;
                        ^
/data/software/sphwvlts//so3/src/c/so3_core.c:527:21: error:
‘ssht_core_mw_lb_inverse_sov_sym_real’ undeclared (first use in this
function)
         real_ssht = ssht_core_mw_lb_inverse_sov_sym_real;
                     ^
/data/software/sphwvlts//so3/src/c/so3_core.c:531:24: error:
‘ssht_core_mw_lb_inverse_sov_sym_ss’ undeclared (first use in this function)
         complex_ssht = ssht_core_mw_lb_inverse_sov_sym_ss;
                        ^
/data/software/sphwvlts//so3/src/c/so3_core.c:532:21: error:
‘ssht_core_mw_lb_inverse_sov_sym_ss_real’ undeclared (first use in this
function)
         real_ssht = ssht_core_mw_lb_inverse_sov_sym_ss_real;
                     ^
/data/software/sphwvlts//so3/src/c/so3_core.c: In function
‘so3_core_forward_via_ssht_real’:
/data/software/sphwvlts//so3/src/c/so3_core.c:752:24: error:
‘ssht_core_mw_lb_forward_sov_conv_sym’ undeclared (first use in this
function)
         complex_ssht = ssht_core_mw_lb_forward_sov_conv_sym;
                        ^
/data/software/sphwvlts//so3/src/c/so3_core.c:753:21: error:
‘ssht_core_mw_lb_forward_sov_conv_sym_real’ undeclared (first use in
this function)
         real_ssht = ssht_core_mw_lb_forward_sov_conv_sym_real;
                     ^
/data/software/sphwvlts//so3/src/c/so3_core.c:757:24: error:
‘ssht_core_mw_lb_forward_sov_conv_sym_ss’ undeclared (first use in this
function)
         complex_ssht = ssht_core_mw_lb_forward_sov_conv_sym_ss;
                        ^
/data/software/sphwvlts//so3/src/c/so3_core.c:758:21: error:
‘ssht_core_mw_lb_forward_sov_conv_sym_ss_real’ undeclared (first use in
this function)
         real_ssht = ssht_core_mw_lb_forward_sov_conv_sym_ss_real;
                     ^
make: **\* [/data/software/sphwvlts//so3/src/c/so3_core.o] Error 1

On 11/13/2015 08:38 AM, Boris Leistedt wrote:

> Hi,
> I've never seem these errors before but I have never compile these
> codes with icc, which might have a different convention for function
> pointers. Would you mind trying to compile with gcc?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/astro-informatics/so3/issues/1#issuecomment-156433109.

## 

Pete Schuck
peter.schuck@nasa.gov
Room 250, Building 21
Space Weather Laboratory, Code 674
Heliophysics Science Division
NASA Goddard Space Flight Center
8800 Greenbelt Rd.
Greenbelt, MD 20771

Work: (301) 286-3008
Cell: (240) 393-9607
 fax: (301) 286-5348   

---

Nullius in verba

For the materialist, science is what teaches us what to believe. For
the empiricist, science is more nearly what teaches us how to give up
our beliefs.  ---  Bas van Fraassen

Because the truth is important --- Jordan Schuck (Age 7)

**Comment by ixkael** [comment] 2015-11-13 14:38
Thanks for trying with GCC. I'm afraid I cannot reproduce this error for some reason. Could you please let me know what OS and compiler versions you use? One way that (I think) could maybe fix this issue is to add "extern" declarations in so3_core.c. For example adding "extern void ssht_core_mw_lb_inverse_sov_sym ... ".

**Comment by pwschuck** [comment] 2015-11-13 16:45
Thanks you for helping!

uname -a

Linux gs674-houdini 3.11.10-29-desktop #1 SMP PREEMPT Thu Mar 5 16:24:00
UTC 2015 (338c513) x86_64 x86_64 x86_64 GNU/Linux

more /etc/SUSE-brand
openSUSE
VERSION = 13.1

 gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib64/gcc/x86_64-suse-linux/4.8/lto-wrapper
Target: x86_64-suse-linux
Configured with: ../configure --prefix=/usr --infodir=/usr/share/info
--mandir=/usr/share/man --libdir=/usr/lib64 --libexecdir=/usr/lib64
--enable-languages=c,c++,objc,fortran,obj-c++,java,ada
--enable-checking=release --with-gxx-include-dir=/usr/include/c++/4.8
--enable-ssp --disable-libssp --disable-plugin
--with-bugurl=http://bugs.opensuse.org/ --with-pkgversion='SUSE Linux'
--disable-libgcj --disable-libmudflap --with-slibdir=/lib64
--with-system-zlib --enable-__cxa_atexit
--enable-libstdcxx-allocator=new --disable-libstdcxx-pch
--enable-version-specific-runtime-libs --enable-linker-build-id
--program-suffix=-4.8 --enable-linux-futex --without-system-libunwind
--with-arch-32=i586 --with-tune=generic --build=x86_64-suse-linux
Thread model: posix
gcc version 4.8.1 20130909 [gcc-4_8-branch revision 202388](SUSE Linux)

Thanks,

-- Pete

On 11/13/2015 09:38 AM, Boris Leistedt wrote:

> Thanks for trying with GCC. I'm afraid I cannot reproduce this error
> for some reason. Could you please let me know what OS and compiler
> versions you use? One way that (I think) could maybe fix this issue is
> to add "extern" declarations in so3_core.c. For example adding "extern
> void ssht_core_mw_lb_inverse_sov_sym ... ".
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/astro-informatics/so3/issues/1#issuecomment-156449748.

## 

Pete Schuck
peter.schuck@nasa.gov
Room 250, Building 21
Space Weather Laboratory, Code 674
Heliophysics Science Division
NASA Goddard Space Flight Center
8800 Greenbelt Rd.
Greenbelt, MD 20771

Work: (301) 286-3008
Cell: (240) 393-9607
 fax: (301) 286-5348   

---

Nullius in verba

For the materialist, science is what teaches us what to believe. For
the empiricist, science is more nearly what teaches us how to give up
our beliefs.  ---  Bas van Fraassen

Because the truth is important --- Jordan Schuck (Age 7)

**Comment by pwschuck** [comment] 2015-11-15 17:48
Hi Boris,

I'm not super comfortable with C so I'm not sure where to add your
suggestion below. Presumably this could all be fixed with a header file
of defs?
Anyway, just as double check, I rebuild everything from scratch with
gcc/gfortran on an independent computer (without intel installed). Same
errors.

fftw - no issues
ssht - no issues, test program runs
so3 - same issues

gcc -Wall -O3 -fopenmp -DSO3_VERSION=\"0.1\" -DSO3_BUILD=\"`git
rev-parse HEAD`\" -I/usr/local/fftw/fftw-3.3.4/include
-I../ssht/include/c -I../so3/include/c -fPIC -c ../so3/src/c/so3_core.c
-o ../so3/src/c/so3_core.o
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
../so3/src/c/so3_core.c: In function ‘so3_core_inverse_via_ssht’:
../so3/src/c/so3_core.c:100:16: error: ‘ssht_core_mw_lb_inverse_sov_sym’
undeclared (first use in this function)
         ssht = ssht_core_mw_lb_inverse_sov_sym;
                ^
../so3/src/c/so3_core.c:100:16: note: each undeclared identifier is
reported only once for each function it appears in
../so3/src/c/so3_core.c:104:16: error:
‘ssht_core_mw_lb_inverse_sov_sym_ss’ undeclared (first use in this function)
         ssht = ssht_core_mw_lb_inverse_sov_sym_ss;
                ^
../so3/src/c/so3_core.c: In function ‘so3_core_forward_via_ssht’:
../so3/src/c/so3_core.c:305:16: error:
‘ssht_core_mw_lb_forward_sov_conv_sym’ undeclared (first use in this
function)
         ssht = ssht_core_mw_lb_forward_sov_conv_sym;
                ^
../so3/src/c/so3_core.c:309:16: error:
‘ssht_core_mw_lb_forward_sov_conv_sym_ss’ undeclared (first use in this
function)
         ssht = ssht_core_mw_lb_forward_sov_conv_sym_ss;
                ^
../so3/src/c/so3_core.c: In function ‘so3_core_inverse_via_ssht_real’:
../so3/src/c/so3_core.c:526:24: error: ‘ssht_core_mw_lb_inverse_sov_sym’
undeclared (first use in this function)
         complex_ssht = ssht_core_mw_lb_inverse_sov_sym;
                        ^
../so3/src/c/so3_core.c:527:21: error:
‘ssht_core_mw_lb_inverse_sov_sym_real’ undeclared (first use in this
function)
         real_ssht = ssht_core_mw_lb_inverse_sov_sym_real;
                     ^
../so3/src/c/so3_core.c:531:24: error:
‘ssht_core_mw_lb_inverse_sov_sym_ss’ undeclared (first use in this function)
         complex_ssht = ssht_core_mw_lb_inverse_sov_sym_ss;
                        ^
../so3/src/c/so3_core.c:532:21: error:
‘ssht_core_mw_lb_inverse_sov_sym_ss_real’ undeclared (first use in this
function)
         real_ssht = ssht_core_mw_lb_inverse_sov_sym_ss_real;
                     ^
../so3/src/c/so3_core.c: In function ‘so3_core_forward_via_ssht_real’:
../so3/src/c/so3_core.c:752:24: error:
‘ssht_core_mw_lb_forward_sov_conv_sym’ undeclared (first use in this
function)
         complex_ssht = ssht_core_mw_lb_forward_sov_conv_sym;
                        ^
../so3/src/c/so3_core.c:753:21: error:
‘ssht_core_mw_lb_forward_sov_conv_sym_real’ undeclared (first use in
this function)
         real_ssht = ssht_core_mw_lb_forward_sov_conv_sym_real;
                     ^
../so3/src/c/so3_core.c:757:24: error:
‘ssht_core_mw_lb_forward_sov_conv_sym_ss’ undeclared (first use in this
function)
         complex_ssht = ssht_core_mw_lb_forward_sov_conv_sym_ss;
                        ^
../so3/src/c/so3_core.c:758:21: error:
‘ssht_core_mw_lb_forward_sov_conv_sym_ss_real’ undeclared (first use in
this function)
         real_ssht = ssht_core_mw_lb_forward_sov_conv_sym_ss_real;
                     ^
makefile:123: recipe for target '../so3/src/c/so3_core.o' failed
make: **\* [../so3/src/c/so3_core.o] Error 1

also I cannot find any defs for ‘ssht_core_mw_lb_inverse_sov_sym’ (and
other functions) in the ssht directory I obtained off of github through
subversion

Thanks,

-- Pete

On 11/13/2015 09:38 AM, Boris Leistedt wrote:

> Thanks for trying with GCC. I'm afraid I cannot reproduce this error
> for some reason. Could you please let me know what OS and compiler
> versions you use? One way that (I think) could maybe fix this issue is
> to add "extern" declarations in so3_core.c. For example adding "extern
> void ssht_core_mw_lb_inverse_sov_sym ... ".
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/astro-informatics/so3/issues/1#issuecomment-156449748.

## 

Pete Schuck
peter.schuck@nasa.gov
Room 250, Building 21
Space Weather Laboratory, Code 674
Heliophysics Science Division
NASA Goddard Space Flight Center
8800 Greenbelt Rd.
Greenbelt, MD 20771

Work: (301) 286-3008
Cell: (240) 393-9607
 fax: (301) 286-5348   

---

Nullius in verba

For the materialist, science is what teaches us what to believe. For
the empiricist, science is more nearly what teaches us how to give up
our beliefs.  ---  Bas van Fraassen

Because the truth is important --- Jordan Schuck (Age 7)

**Comment by ixkael** [comment] 2015-11-16 16:01
Hi Pete,

OK I found the issue - this is actually a real problem so unrelated to your machine or install, sorry about the confusion and waste of time. The version of SSHT on github is not the latest for some reason. I will fix this as soon as possible so that you can pull the actual version needed by SO3. 

Best,
Boris

**Comment by pwschuck** [comment] 2015-11-16 16:04
Thank you so much Boris! I suspected that this might be the problem
after I searched the SSHT install for the missing functions with no
positive results

-- Pete

On 11/16/2015 11:01 AM, Boris Leistedt wrote:

> Hi Pete,
> 
> OK I found the issue - this is actually a real problem so unrelated to
> your machine or install, sorry about the confusion and waste of time.
> The version of SSHT on github is not the latest for some reason. I
> will fix this as soon as possible so that you can pull the actual
> version needed by SO3.
> 
> Best,
> Boris
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/astro-informatics/so3/issues/1#issuecomment-157079404.

## 

Pete Schuck
peter.schuck@nasa.gov
Room 250, Building 21
Space Weather Laboratory, Code 674
Heliophysics Science Division
NASA Goddard Space Flight Center
8800 Greenbelt Rd.
Greenbelt, MD 20771

Work: (301) 286-3008
Cell: (240) 393-9607
 fax: (301) 286-5348   

---

Nullius in verba

For the materialist, science is what teaches us what to believe. For
the empiricist, science is more nearly what teaches us how to give up
our beliefs.  ---  Bas van Fraassen

Because the truth is important --- Jordan Schuck (Age 7)

**Comment by ixkael** [comment] 2015-11-18 21:01
Hi,
Jason and I just fixed the problem and pushed a new version of SSHT to github. Could you please try to install SSHT + SO3 and see if this has resolved the problem?
Thanks,
Boris

**Comment by pwschuck** [comment] 2015-11-19 13:18
Hi Boris & Jason,

That fixed it! I was able to build and run the test programs for
ssht/so2/s2let

Thank you very much for your efforts.

-- Pete

On 11/18/2015 04:01 PM, Boris Leistedt wrote:

> Hi,
> Jason and I just fixed the problem and pushed a new version of SSHT to
> github. Could you please try to install SSHT + SO3 and see if this has
> resolved the problem?
> Thanks,
> Boris
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/astro-informatics/so3/issues/1#issuecomment-157862296.

## 

Pete Schuck
peter.schuck@nasa.gov
Room 250, Building 21
Space Weather Laboratory, Code 674
Heliophysics Science Division
NASA Goddard Space Flight Center
8800 Greenbelt Rd.
Greenbelt, MD 20771

Work: (301) 286-3008
Cell: (240) 393-9607
 fax: (301) 286-5348   

---

Nullius in verba

For the materialist, science is what teaches us what to believe. For
the empiricist, science is more nearly what teaches us how to give up
our beliefs.  ---  Bas van Fraassen

Because the truth is important --- Jordan Schuck (Age 7)

**Comment by ixkael** [comment] 2015-11-19 16:18
Brilliant! I'll close the issue then.

Boris

**Closed as completed by ixkael** 2015-11-19 16:18 UTC
